#!/bin/bash
#
# Usage:
# $ bm [command] [arguments]
# 
# Commands:
# bm [path]
# cd index
# clear
# list
#
# Positional arguments:
# * [path]: Filepath to bookmark, defaults to current directory
# * index: Number of bookmark to navigate to 

# Main launcher --------------------------------------------------------------

bm () {
	cmd=$1
	if type "bm__$cmd" >/dev/null 2>&1; then
		shift
		"bm__$cmd" "$@"
	else
		bookmark=${1:-$(pwd)}
		echo "$bookmark" >> $HOME/.bookmarks
	fi	
}

# Individual commands -------------------------------------------------------- 

bm__cd() { 
	if [ -f "$HOME/.bookmarks" ]; then	
		dest=$(cat $HOME/.bookmarks | sed -n "$1p")
		cd $dest
	else
		echo "No existing bookmarks, create one with 'bm [path]'"
	fi
}

bm__clear() { rm "$HOME/.bookmarks"; }

bm__list() { 
	if [ -f "$HOME/.bookmarks" ]; then
		cat -n "$HOME/.bookmarks"
	else
		echo "No existing boomarks, create one with 'bm [path]'"
	fi
}
