#!/bin/bash

# INSTALL: source this file in your ~/.bashrc
#
# Bookmark directories to easily navigate there later
#
# Usage:
# $ bm [command] [arguments]
# 
# Commands:
# bm [path]
# bm cd index
# bm clear [index]
# bm list
#
# Positional Arguments:
# * path: Filepath to bookmark, defaults to current directory
# * index: Number of bookmark to navigate to or clear

# Main launcher --------------------------------------------------------------

bm () {
    cmd=$1
    if type "bm__$cmd" >/dev/null 2>&1; then
        shift
        "bm__$cmd" "$@"
    else
        bookmark=${1:-$(pwd)}
        echo "$bookmark" >> "$HOME/.bookmarks"
        cat "$HOME/.bookmarks" | sort | uniq >> "$HOME/.bookmarks.tmp"
        mv "$HOME/.bookmarks.tmp" "$HOME/.bookmarks" 
    fi	
}

# Individual commands -------------------------------------------------------- 

bm__cd() { 
    if [ -f "$HOME/.bookmarks" ]; then	
        dest=$(cat $HOME/.bookmarks | sed -n "$1p")
        cd $dest
    else
        echo "No existing bookmarks, create one with 'bm [path]'"
    fi
}

bm__clear() { 
    if [ -z "$1" ]; then
        rm "$HOME/.bookmarks"
    else
        sed -i "$1d" "$HOME/.bookmarks"
    fi
}

bm__list() { 
    if [ -f "$HOME/.bookmarks" ]; then
        cat -n "$HOME/.bookmarks"
    else
        echo "No existing boomarks, create one with 'bm [path]'"
    fi
}
