#!/bin/bash

# INSTALL: symlink or copy this file to /usr/local/bin
#
# Count files in a directory with a given ending
#
# Usage:
# $ count [-a] [-E] [-r] [-u] [-v] [-d file_path] [regex]
#
# Positional Arguments:
# * [regex]: Passed to grep to filter files, defaults to match all files
#
# Options:
# * [-a]: Include hidden files and directories
# * [-d file_path]: Folder to count files for, defaults to current directory
# * [-E]: Enable extended regular expressions (i.e. egrep or grep -E)
# * [-r]: Recursive, count files from file_path downwards
# * [-u]: Display unique file extensions with their counts
# * [-v]: Invert the sense of the match, count non-matching files

# Parese CLI optional and positional arguments -------------------------------
while getopts "ad:Eruv" opt; do
    case $opt in
        a)
            hidden=true;;
        d)
            file_path=$OPTARG;;
        E)
            extended=true;;
        r)
            recursive=true;;
        u)
            unique=true;;
        v)
            invert=true;;
        \?)
            exit 1;;
        :)
            exit 1;;
    esac
done

hidden=${hidden:-false}
extended=${extended:-false}
recursive=${recursive:-false}
unique=${unique:-false}
invert=${invert:-false}
file_path=${file_path:-$(pwd)}
if [[ ! -d "$file_path" ]]; then
    echo "$file_path is not a directory"
    exit 1
fi
shift $((OPTIND - 1))
if [[ "$unique" == true && ! -z $1 ]]; then
    echo "Warning: option '-u' may not be meaningful if regex is supplied"
fi 
regex=\"${1:-.*}\"

# Generate output ------------------------------------------------------------
if [[ "$extended" = true ]]; then
    search="egrep $regex"
else
    search="grep $regex"
fi

if [[ "$invert" == true ]]; then
    search="$search -v"
fi

files="find $filepath"
if [[ "$recursive" == false ]]; then
    files="$files -maxdepth 1"
fi

if [[ "$hidden" == false ]]; then
    files="$files -not -path '*/\.*'"
fi
files="$files -type f -printf '%f\n'"

if [[ "$unique" == true ]]; then
    display="sed '/\./! s/.*/ None/' | sed 's/^.*\./ \*\./' | sort | uniq -c"
else
    display="wc -l"
fi

cmd="${files} | ${search} | ${display}"
eval $cmd
