#!/bin/bash

# INSTALL: symlink or copy this file to /usr/local/bin
#
# Count files in a directory with a given ending
#
# Usage:
# $ count [-a] [-d directory] [-E] [-r] [-v] [regex]
#
# Positional Arguments:
# * [regex]: Passed to grep to filter files, defaults to match all files
#
# Options:
# * [-a]: Include hidden files and directories
# * [-d directory]: Relative path for folder to count files for, default none
# * [-E]: Enable extended regular expressions (i.e. egrep or grep -E)
# * [-r]: Recursive, count files from file_path downwards
# * [-v]: Invert the sense of the match, count non-matching files

# Parese CLI optional and positional arguments -------------------------------
while getopts "ad:Erv" opt; do
    case $opt in
        a)
            hidden=true;;
        d)
            file_path=$OPTARG;;
        E)
            extended=true;;
        r)
            recursive=true;;
        v)
            invert=true;;
        \?)
            exit 1;;
        :)
            exit 1;;
    esac
done

hidden=${hidden:-false}
extended=${extended:-false}
recursive=${recursive:-false}
invert=${invert:-false}
file_path="$(pwd)/$file_path"
if [[ ! -d "$file_path" ]]; then
    echo "$file_path is not a directory"
    exit 1
fi
shift $((OPTIND - 1))
if [[ -z "$1" ]]; then
    all=true
fi
all=${all:-false}
regex=\"${1:-.*}\"

# Generate output ------------------------------------------------------------
files="find ${file_path}"
if [[ "$recursive" == false ]]; then
    files="${files} -maxdepth 1"
fi

if [[ "$hidden" == false ]]; then
    files="${files} -not -path '*/\.*'"
fi
files="${files} -type f -printf '%f\n'"

if [[ "$all" == true ]]; then
    substitutions="sed '/\./! s/.*/ None/' | sed 's/^.*\./ \*\./'"
    cmd="${files} | ${substitutions} | sort | uniq -c | sort -nrk1"
else
    if [[ "$extended" = true ]]; then
        search="egrep ${regex}"
    else
        search="grep ${regex}"
    fi
    if [[ "$invert" == true ]]; then
        search="${search} -v"
    fi
    cmd="${files} | ${search} | wc -l"
fi

eval $cmd
