#! /bin/bash

echo "# Added by bash-utils installer" >> ~/.bashrc
echo "source /usr/local/bin/bm" >> ~/.bashrc
echo "source /usr/local/bin/up" >> ~/.bashrc
echo "Please run source ~/.bashrc to complete setup"
